### PR TITLE
Fix dependencies

### PR DESCRIPTION
**Pull request by marcantoinecouture**
Fix messages and services dependencies

### CODE REVIEW

**Comment by gauthiermartin** [comment]
@coumarc9  Still usefull ?

**Comment by marcantoinecouture** [comment]
@gauthiermartin Since we don't have the new telemetry yet, yes this is usefull

**Review by gauthiermartin — CHANGES_REQUESTED** [review]
We should change sonia_msgs for sonia_common

**Comment by marcantoinecouture** [comment]
I agree, I think we should add it to sonia-auv/sonia_common#4.

**Pull request closed without merging**
